#!/bin/bash
set -e

psql -v  ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
	CREATE USER $MTTG_USER ENCRYPTED PASSWORD '$MTTG_PASSWORD';
	CREATE DATABASE mttg;
	GRANT ALL PRIVILEGES ON DATABASE mttg TO $MTTG_USER;
EOSQL
